# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Formats to build
formats: []  # Only build HTML for now

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
